// examples/react/src/components/HelloWorldA.tsx
import { useState } from 'react';

function HelloWorld(props: { msg: string }) {
    const [count, setCount] = useState(0);

    return (
        <>
            <h1>Group A</h1>
            <h1>{props.msg}</h1>
            <div className="card">
                <button onClick={() => setCount(count => count + 1)}>
                    count is
                    {' '}
                    {count}
                </button>
                <p>
                    Edit
                    {' '}
                    <code>src/App.tsx</code>
                    {' '}
                    and save to test HMR
                </p>
            </div>
            <p className="read-the-docs">
                Click on the Vite and React logos to learn more
            </p>
        </>
    );
}

export default HelloWorld;

// examples/vue/src/components/HelloWorldA.vue
<script setup lang="ts">
import { ref } from 'vue';

defineProps<{ msg: string }>();

const count = ref(0);
</script>

<template>
    <h1>{{ msg }}</h1>
    <h1>Group A</h1>

    <div class="card">
        <button type="button" @click="count++">
            count is {{ count }}
        </button>
        <p>
            Edit
            <code>components/HelloWorld.vue</code> to test HMR
        </p>
    </div>

    <p>
        Check out
        <a href="https://vuejs.org/guide/quick-start.html#local" target="_blank">create-vue</a>, the official Vue + Vite starter
    </p>
    <p>
        Install
        <a href="https://github.com/vuejs/language-tools" target="_blank">Volar</a>
        in your IDE for a better DX
    </p>
    <p class="read-the-docs">
        Click on the Vite and Vue logos to learn more
    </p>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
