// examples/vue/src/App.vue
<script setup lang="ts">
import type { ABKey } from 'vue-ab-hoc';
import { abKeys } from './global';
import HelloWorld from './components/HelloWorld';

function setAbKey(keys: ABKey) {
    abKeys.value = [keys];
}
</script>

<template>
    <div>
        <a href="https://vitejs.dev" target="_blank">
            <img src="/vite.svg" class="logo" alt="Vite logo">
        </a>
        <a href="https://vuejs.org/" target="_blank">
            <img src="./assets/vue.svg" class="logo vue" alt="Vue logo">
        </a>
    </div>

    <button class="btn" @click="setAbKey('s_base')">
        Group Base
    </button>
    <button class="btn" @click="setAbKey('s_a')">
        Group A
    </button>
    <button class="btn" @click="setAbKey('s_b')">
        Group B
    </button>
    <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
}
.logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
    filter: drop-shadow(0 0 2em #42b883aa);
}
.btn {
    margin-left: 1em;
}
.btn:first-of-type {
    margin-left: 0;
}
</style>

// examples/react/src/App.tsx
import { Suspense, useState } from 'react';
import { type ABKey, AbContext } from 'react-ab-hoc';
import HelloWorld from './components/HelloWorld';
import reactLogo from './assets/react.svg';
import viteLogo from '/vite.svg';
import './App.css';

function App() {
    const [abKeys, setAbKeys] = useState<ABKey[]>([]);

    return (
        <Suspense>
            <AbContext.Provider value={abKeys}>
                <div>
                    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
                        <img src={viteLogo} className="logo" alt="Vite logo" />
                    </a>
                    <a href="https://react.dev" target="_blank" rel="noreferrer">
                        <img src={reactLogo} className="logo react" alt="React logo" />
                    </a>
                </div>

                <button onClick={() => setAbKeys(['s_base'])}>Group Base</button>
                <button style={{ marginLeft: '1em' }} onClick={() => setAbKeys(['s_a'])}>Group A</button>
                <button style={{ marginLeft: '1em' }} onClick={() => setAbKeys(['s_b'])}>Group B</button>
                <HelloWorld msg="Vite + React" />
            </AbContext.Provider>
        </Suspense>
    );
}

export default App;
